### ISSUE TITLE
[FEATURE] Get random greeting for the hello command

### ISSUE THREAD

**Issue by misslame** [misslame/BroncoderBot#7]
https://perchance.org/greeting get a random greeting from this. Beautiful soup it 

Should say the greeting and then mention the user after they use the /hello command

**Comment by Benjamin-Ung** [comment]
Because the website uses javascript to create a response upon loading the web page, you need to use selenium in conjunction with beautifulsoup for dyanmic scraping

**Comment by notpallav** [comment]
I dont think we need selenium.
We can get the full list by either  visiting the site, type 111 for amount and select unique. 
Or if you still want to have the bot fetch the list (the list is static so not sure why), you can just fetch it using requests/whatever then parse the response to get the contents of the script tag with the id "preloaded-generator-data", then url-decode -> jsonify -> get the responses under the key "outputTemplate" and do some processing magic
